version: "3.9"

services:
  django_gunicorn:
    build:
      context: .
    restart: always
    volumes:
      - static:/static
    environment:
      - DEBUG=${DEBUG}
      - SETTINGS_SECRET_KEY=${SETTINGS_SECRET_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
