version: '3.9'

services:
  django_gunicorn:
    build:
      context: .
    stop_signal: SIGINT
    volumes:
      - static:/static
    ports:
      - "8080:8080"
    env_file:
      - .env

  proxy:
    build: ./proxy
    volumes:
      - static:/static
    ports:
      - "80:8080"
    depends_on:
      - django_gunicorn

volumes:
  static: