version: '3.9'

services:
  django_gunicorn:
    build:
      context: .
    ports:
      - "8080:80"
    restart: always
    env_file:
      - .env
    volumes:
      - ./frukt/db.sqlite3:/app/db.sqlite3


  proxy:
    build: ./proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - django_gunicorn
