version: '3.9'

services:
  django_gunicorn:
    build:
      context: .
    stop_signal: SIGQUIT
    ports:
      - "8080:80"
    restart: always
    env_file:
      - .env

  proxy:
    build: ./proxy
    stop_signal: SIGQUIT
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - django_gunicorn
