version: '3.9'

services:
  django_gunicorn:
    build:
      context: .
    stop_signal: SIGQUIT
#    volumes:
#      - static:/static
    ports:
      - "8080:80"
    env_file:
      - .env

  proxy:
    build: ./proxy
    stop_signal: SIGQUIT
#    volumes:
#      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static: