version: "3.11"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - "80:8080"
    volumes:
      - static-data:/vol/static

volumes:
  static-data: