version: "3.9"

services:
  django_gunicorn:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - django_gunicorn
    ports:
      - "80:8080"
    volumes:
      - static-data:/vol/static

volumes:
  static-data: