version: '3.11'

services:
  django_gunicorn:
    build:
      context: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8080"
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1

