version: "3.11"

services:
  django_gunicorn:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}


  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - frukt
    ports:
      - 80:8080
    volumes:
      - static-data:/vol/static