# Generated by Django 4.1.4 on 2023-02-02 12:50

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='', max_length=60)),
                ('slug', models.SlugField(default='', max_length=60, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=160, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
